import os
import codecs

def readFile(path):
    try:
        fp = open(path, encoding="utf-8")
        content = fp.read()
        fp.close()
        return content
    except:
        fp = open(path, encoding="gbk")
        content = fp.read()
        fp.close()
        return content

def writeFile(path, content):
    fp = open(path, "wb")
    buffer = codecs.encode(content, "utf-8")
    fp.write(buffer)
    fp.close()
    return content

def gen():
    dirname = "visitors"

    files = os.listdir(dirname)

    blacklist = ["gen_tm2c.py", "tm2c.py", "common.py"]

    head = "from context import *\n"
    head += "from parse import *\n"
    head += "import sys\n"
    head += "# this file is auto-generated by gen_tm2c.py\n"

    content = head;

    for fname in files:
        if not fname.endswith(".py"):
            continue
        elif fname in blacklist:
            continue
        fname = os.path.join(dirname, fname)
        name = fname.split(".")[0]

        content += readFile(fname)
        content += "\n"

    content += readFile("common.py")
    
    writeFile("tm2c.py", content)


if __name__ == '__main__':
    gen()