/*
* @author xupingmao<578749341@qq.com>
* @generated by Python
* @date Sun Aug 09 11:32:11 2015
*/
#ifndef INSTRUCTION_H_
#define INSTRUCTION_H_
#define NEW_STRING 1
#define NEW_NUMBER 2
#define ADD 3
#define SUB 4
#define MUL 5
#define DIV 6
#define MOD 7
#define NEG 8
#define NOT 9
#define GT 10
#define LT 11
#define GTEQ 12
#define LTEQ 13
#define EQEQ 14
#define NOTEQ 15
#define OP_IN 16
#define NOTIN 17
#define AND 18
#define OR 19
#define SET 20
#define GET 21
#define LOAD_NONE 22
#define STORE_LOCAL 23
#define STORE_GLOBAL 24
#define LOAD_LOCAL 25
#define LOAD_GLOBAL 26
#define LOAD_CONSTANT 27
#define LOAD_GLOBALS 28
#define POP 29
#define DICT_SET 30
#define LIST 31
#define DICT 32
#define LIST_APPEND 33
#define JUMP 34
#define UP_JUMP 35
#define POP_JUMP_ON_FALSE 36
#define JUMP_ON_FALSE 37
#define JUMP_ON_TRUE 38
#define TM_UNARRAY 39
#define TM_ROT 40
#define TM_DEL 41
#define TM_FOR 42
#define TM_NEXT 43
#define ITER_NEW 44
#define LOAD_EX 45
#define SETJUMP 46
#define CALL 47
#define TM_DEF 48
#define RETURN 49
#define LOAD_PARAMS 50
#define TM_NARG 51
#define TM_EOF 52
#define TM_EOP 53
#define TM_DEBUG 54
#define TAG 55
#define FAST_ST_GLO 56
#define FAST_LD_GLO 57
#define LT_JUMP_ON_FALSE 58
#define GT_JUMP_ON_FALSE 59
#define LTEQ_JUMP_ON_FALSE 60
#define GTEQ_JUMP_ON_FALSE 61
#define EQEQ_JUMP_ON_FALSE 62
#define NOTEQ_JUMP_ON_FALSE 63
#endif

