/*
* @author xupingmao<578749341@qq.com>
* @generated by Python
* @date Mon Mar 28 23:51:46 2016
*/
#ifndef INSTRUCTION_H_
#define INSTRUCTION_H_
#define NEW_STRING 1
#define NEW_NUMBER 2
#define OP_IMPORT 3
#define ADD 4
#define SUB 5
#define MUL 6
#define DIV 7
#define MOD 8
#define NEQ 9
#define GT 10
#define LT 11
#define GTEQ 12
#define LTEQ 13
#define EQEQ 14
#define NOTEQ 15
#define OP_IN 16
#define NOTIN 17
#define OP_AND 18
#define OP_OR 19
#define SET 20
#define GET 21
#define NOT 22
#define MOV 23
#define NEG 24
#define LISTAPPEND 25
#define LD_NONE 26
#define LIST 27
#define DICT 28
#define SETG 29
#define LD_CONST 30
#define GETG 31
#define JF 32
#define TM_LINE 33
#define JMP 34
#define UP_JMP 35
#define CALL0 36
#define CALL1 37
#define CALL2 38
#define CALL3 39
#define CALL4 40
#define CALL5 41
#define RET 42
#define TM_DEF 43
#define NARG 44
#define POP_JUMP_ON_FALSE 45
#define JUMP_ON_FALSE 46
#define JUMP_ON_TRUE 47
#define TM_UNARRAY 48
#define TM_ROT 49
#define TM_DEL 50
#define TM_FOR 51
#define TM_NEXT 52
#define ITER_NEW 53
#define LOAD_EX 54
#define SETJUMP 55
#define CALL 56
#define RETURN 57
#define LOAD_PARAMS 58
#define TM_NARG 59
#define TM_EOF 60
#define CLRJUMP 61
#define TM_EOP 62
#define TM_DEBUG 63
#define TAG 64
#define FAST_ST_GLO 65
#define FAST_LD_GLO 66
#endif

