/*
* @author xupingmao<578749341@qq.com>
* @generated by Python
* @date Sun Apr  3 17:37:05 2016
*/
#ifndef INSTRUCTION_H_
#define INSTRUCTION_H_
#define NEW_STRING 1
#define NEW_NUMBER 2
#define OP_IMPORT 3
#define ADD 4
#define SUB 5
#define MUL 6
#define DIV 7
#define MOD 8
#define NEG 9
#define NOT 10
#define OP_GT 11
#define OP_LT 12
#define GTEQ 13
#define LTEQ 14
#define EQEQ 15
#define NOTEQ 16
#define OP_IN 17
#define NOTIN 18
#define AND 19
#define OR 20
#define SET 21
#define GET 22
#define LOAD_NONE 23
#define STORE_LOCAL 24
#define STORE_GLOBAL 25
#define LOAD_LOCAL 26
#define LOAD_GLOBAL 27
#define LOAD_CONSTANT 28
#define POP 29
#define DICT_SET 30
#define LIST 31
#define DICT 32
#define LIST_APPEND 33
#define JUMP 34
#define UP_JUMP 35
#define POP_JUMP_ON_FALSE 36
#define JUMP_ON_FALSE 37
#define JUMP_ON_TRUE 38
#define TM_UNARRAY 39
#define TM_ROT 40
#define TM_DEL 41
#define TM_FOR 42
#define TM_NEXT 43
#define ITER_NEW 44
#define LOAD_EX 45
#define SETJUMP 46
#define CALL 47
#define TM_DEF 48
#define RETURN 49
#define LOAD_PARAMS 50
#define TM_NARG 51
#define TM_EOF 52
#define CLRJUMP 53
#define TM_EOP 54
#define TM_DEBUG 55
#define TM_LINE 56
#define TAG 57
#define FAST_ST_GLO 58
#define FAST_LD_GLO 59
#endif

