/*
* @author xupingmao<578749341@qq.com>
* @generated by Python
* @date Fri Sep  1 10:07:29 2017
*/
#ifndef INSTRUCTION_H_
#define INSTRUCTION_H_
#define OP_STRING 1
#define OP_NUMBER 2
#define OP_IMPORT 3
#define OP_ADD 4
#define OP_SUB 5
#define OP_MUL 6
#define OP_DIV 7
#define OP_MOD 8
#define OP_NEG 9
#define OP_NOT 10
#define OP_GT 11
#define OP_LT 12
#define OP_GTEQ 13
#define OP_LTEQ 14
#define OP_EQEQ 15
#define OP_NOTEQ 16
#define OP_IN 17
#define OP_NOTIN 18
#define OP_AND 19
#define OP_OR 20
#define OP_SET 21
#define OP_GET 22
#define OP_SLICE 23
#define OP_NONE 24
#define OP_STORE_LOCAL 25
#define OP_STORE_GLOBAL 26
#define OP_LOAD_LOCAL 27
#define OP_LOAD_GLOBAL 28
#define OP_CONSTANT 29
#define OP_POP 30
#define OP_DICT_SET 31
#define OP_LIST 32
#define OP_DICT 33
#define OP_APPEND 34
#define OP_JUMP 35
#define OP_UP_JUMP 36
#define OP_POP_JUMP_ON_FALSE 37
#define OP_JUMP_ON_FALSE 38
#define OP_JUMP_ON_TRUE 39
#define OP_UNPACK 40
#define OP_ROT 41
#define OP_DEL 42
#define OP_FOR 43
#define OP_NEXT 44
#define OP_ITER 45
#define OP_LOAD_EX 46
#define OP_SETJUMP 47
#define OP_CALL 48
#define OP_TAILCALL 49
#define OP_APPLY 50
#define OP_DEF 51
#define OP_RETURN 52
#define OP_LOAD_PARAMS 53
#define OP_LOAD_NARG 54
#define OP_LOAD_PARG 55
#define OP_EOF 56
#define OP_CLR_JUMP 57
#define OP_EOP 58
#define OP_DEBUG 59
#define OP_LINE 60
#define OP_TAG 61
#define OP_FAST_ST_GLO 62
#define OP_FAST_LD_GLO 63
#define OP_FILE 64
#endif

