/*
* @author xupingmao<578749341@qq.com>
* @generated by Python
* @date Sat Nov 12 23:29:33 2016
*/
#ifndef INSTRUCTION_H_
#define INSTRUCTION_H_
#define OP_STRING 1
#define OP_NUMBER 2
#define OP_IMPORT 3
#define OP_ADD 4
#define OP_SUB 5
#define OP_MUL 6
#define OP_DIV 7
#define OP_MOD 8
#define OP_NEG 9
#define OP_NOT 10
#define OP_GT 11
#define OP_LT 12
#define OP_GTEQ 13
#define OP_LTEQ 14
#define OP_EQEQ 15
#define OP_NOTEQ 16
#define OP_IN 17
#define OP_NOTIN 18
#define OP_AND 19
#define OP_OR 20
#define OP_SET 21
#define OP_GET 22
#define OP_NONE 23
#define OP_STORE_LOCAL 24
#define OP_STORE_GLOBAL 25
#define OP_LOAD_LOCAL 26
#define OP_LOAD_GLOBAL 27
#define OP_CONSTANT 28
#define OP_POP 29
#define OP_DICT_SET 30
#define OP_LIST 31
#define OP_DICT 32
#define OP_APPEND 33
#define OP_JUMP 34
#define OP_UP_JUMP 35
#define OP_POP_JUMP_ON_FALSE 36
#define OP_JUMP_ON_FALSE 37
#define OP_JUMP_ON_TRUE 38
#define OP_UNPACK 39
#define OP_ROT 40
#define OP_DEL 41
#define OP_FOR 42
#define OP_NEXT 43
#define OP_ITER 44
#define OP_LOAD_EX 45
#define OP_SETJUMP 46
#define OP_CALL 47
#define OP_DEF 48
#define OP_RETURN 49
#define OP_LOAD_PARAMS 50
#define OP_LOAD_NARG 51
#define OP_LOAD_PARG 52
#define OP_EOF 53
#define OP_CLR_JUMP 54
#define OP_EOP 55
#define OP_DEBUG 56
#define OP_LINE 57
#define OP_TAG 58
#define OP_FAST_ST_GLO 59
#define OP_FAST_LD_GLO 60
#endif

